version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: '9.0'
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: cd ios && fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: CircleCIDemoReactNative
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-result
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
  build:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build .
  print-version:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run: node --version
      - run: npm --version
  test:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-package-{{ checksum "yarn.lock" }}
      - run:
          name: Install depedencies
          command: yarn install --immutable
      - run:
          name: Run tests
          command: yarn test
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-package-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged

workflows:
  build-and-test:
    jobs:
      - build-and-test
  test-deploy:
    jobs:
      - build
      - print-version
      - test:
          requires:
            - print-version
