version: 2.1

jobs:
  install-dependencies:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-package-{{ checksum "yarn.lock" }}
      - run:
          name: Install depedencies
          command: yarn install --immutable
  save-cache:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-package-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
  test:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: yarn test

workflows:
  test-deploy:
    jobs:
      - install-dependencies
      - test:
          requires:
            - install-dependencies
      - save-cache:
          requires:
            - test
