version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run:
        name: Install depedencies
        command: yarn install --immutable
      # - run:
      #   name: Run tests
      #   command: yarn test
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!'

workflows:
  test-deploy:
    jobs:
      - test
