version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.8.0-stretch-browers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build .
  print-version:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run: node --version
      - run: npm --version
  test:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-package-{{ checksum "yarn.lock" }}
      - run:
          name: Install depedencies
          command: yarn install --immutable
      - run:
          name: Run tests
          command: yarn test
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-package-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged

workflows:
  test-deploy:
    jobs:
      - build
      - print-version
      - test:
          requires:
            - print-version
