version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "hello world"
  build-android:
    docker:
      - image: cimg/android:2021.10.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "hello world"
  build-macos:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: echo "hello world"

workflows:
  build-different-hello-world:
    jobs:
      - build
      - build-android
      - build-macos
